#!/usr/bin/env bash
# Regenerates the static content of helm/cubestack-operator from the kustomize
# sources in config/. Idempotent: run after any change under config/ and commit
# the chart. CI runs this script and fails on git diff (make helm-resources-check).
#
# The chart ships ONLY the ai.cubestack.io CRDs (copied below from
# config/crd/bases). The leaderworkerset/disaggregatedset CRDs are NOT shipped
# by the chart — they come with the upstream LeaderWorkerSet controller
# prerequisite (hack/install-lws-controller.sh applies the pinned lws module's
# config/default, which includes its own CRDs).
set -euo pipefail
cd "$(dirname "$0")/.."          # operator/
OP="${PWD}"
CHART="${OP}/helm/cubestack-operator"
TEMPLATES="${CHART}/templates"
CRDS="${CHART}/crds"

# --- 1. CRDs: ai CRDs from config/crd/bases (verbatim, unprefixed) ---
# The lws/disaggregatedset CRDs are deliberately absent: they are installed by
# the LeaderWorkerSet controller prerequisite (see header comment).
rm -rf "${CRDS}" "${TEMPLATES}"
mkdir -p "${CRDS}" "${TEMPLATES}"
cp "${OP}"/config/crd/bases/*.yaml "${CRDS}"/

# --- 2. VAPs: verbatim from config/vap (source of truth, unprefixed) ---
# Join with explicit "---" separators: each source file is its own multi-doc
# stream, and without a separator the last doc of one file would merge into
# the first doc of the next (duplicate keys are silently overwritten by the
# YAML decoders helm uses, dropping whole documents).
{
  cat "${OP}"/config/vap/modelversion_policy.yaml
  for f in "${OP}"/config/vap/inferenceruntimeprofile_policy.yaml \
           "${OP}"/config/vap/inferenceservice_policy.yaml; do
    printf -- '---\n'
    cat "${f}"
  done
} > "${TEMPLATES}"/vap.yaml
sed -i '1i # Generated by hack/update-helm-resources.sh — DO NOT EDIT' "${TEMPLATES}"/vap.yaml

# --- 3. RBAC / manager / metrics Service: split kustomize build output ---
if [ ! -x "${OP}/bin/kustomize" ]; then
  make -s -C "${OP}" kustomize
fi
OUT="$(mktemp)"
trap 'rm -f "${OUT}"' EXIT
"${OP}/bin/kustomize" build "${OP}/config/default" > "${OUT}"

# Rewrite the manager image to values references. The images transformer in
# config/manager/kustomization.yaml already rewrote controller:latest to
# example.com/cubestack:v0.0.1 in the build output.
sed -i 's|^\(\s*\)image: example\.com/cubestack:v0\.0\.1$|\1image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"|' "${OUT}"
# Fail loudly if the needle above matched nothing (e.g. the images transformer
# in config/manager/kustomization.yaml changed): a silent no-op would leave a
# stale hardcoded image in the chart while the drift gate stays green.
grep -q 'image: "{{ .Values.image' "${OUT}" || { echo "image rewrite no-op'd — update needle in update-helm-resources.sh"; exit 1; }
# Replace the hardcoded namespace (metadata + binding subjects) with the release ns.
sed -i 's|namespace: cubestack-system|namespace: {{ .Release.Namespace }}|g' "${OUT}"

awk -v out="${TEMPLATES}" '
function flush() {
  if (buf == "") return
  # Skip objects handled above (CRDs/VAPs) or not owned by the chart (Namespace).
  if (kind == "CustomResourceDefinition" || kind == "ValidatingAdmissionPolicy" || kind == "ValidatingAdmissionPolicyBinding" || kind == "Namespace") { buf=""; kind=""; name=""; return }
  base = tolower(kind) "-" name
  gsub(/[^a-z0-9-]/, "-", base)
  fn = out "/" base ".yaml"
  print "# Generated by hack/update-helm-resources.sh — DO NOT EDIT" > fn
  printf "%s\n", buf > fn
  close(fn)
  buf=""; kind=""; name=""
}
/^---$/ { flush(); next }
# Capture the first kind and first two-space-indented name of each doc (the
# metadata.name); apiVersion is the first line, so capture must not depend on
# the buffer being empty.
{ if (kind == "" && $0 ~ /^kind: /) kind = $2
  if (name == "" && $0 ~ /^  name: /) name = $2
  buf = buf $0 "\n" }
END { flush() }
' "${OUT}"
rm -f "${OUT}"
echo "chart resources regenerated under ${CHART}"
